### ISSUE TITLE
Crashing when i try to enable it in the dev menu

### ISSUE THREAD

**Issue by MarioMastr** [CalcuIator/v4-S3#3]
Loaded Data File 'Bytecode/GlobalCode.bin'
loaded datapack 'Data.rsdk'
Loaded Data File 'Data/Game/GameConfig.bin'
Initializing gamepads...
Found 0 gamepads!
Loaded Data File 'Data/Game/GameConfig.bin'
Set SFX (0) name to: Jump
Set SFX (1) name to: Ring L
Set SFX (2) name to: Ring R
Set SFX (3) name to: Skidding
Set SFX (4) name to: Lose Rings
Set SFX (5) name to: Hurt
Set SFX (6) name to: Charge
Set SFX (7) name to: Release
Set SFX (8) name to: Destroy
Set SFX (9) name to: Lamp Post
Set SFX (10) name to: Blue Shield
Set SFX (11) name to: Spring
Set SFX (12) name to: Sign Post
Set SFX (13) name to: Score Add
Set SFX (14) name to: Score Total
Set SFX (15) name to: Special Ring
Set SFX (16) name to: Warp
Set SFX (17) name to: Explosion
Set SFX (18) name to: Rolling
Set SFX (19) name to: Flying
Set SFX (20) name to: Tired
Set SFX (21) name to: Menu Move
Set SFX (22) name to: Menu Select
Set SFX (23) name to: Menu Back
Set SFX (24) name to: Life
Set SFX (25) name to: Landing
Set SFX (26) name to: Sliding
Set SFX (27) name to: Catch
Set SFX (28) name to: Bonus Points
Set SFX (29) name to: Spikes Move
Set SFX (30) name to: Bubble Shield
Set SFX (31) name to: Bubble Bounce
Set SFX (32) name to: Fire Shield
Set SFX (33) name to: Fire Dash
Set SFX (34) name to: Lightning Shield
Set SFX (35) name to: Lightning Jump
Set SFX (36) name to: Insta Shield
Set SFX (37) name to: Transform
Set SFX (38) name to: Spike
Set SFX (39) name to: Event
Set SFX (40) name to: Resume
Loaded Data File 'Data/SoundFX/Global/Jump.wav'
Loaded Data File 'Data/SoundFX/Global/Ring.wav'
Loaded Data File 'Data/SoundFX/Global/Ring.wav'
Loaded Data File 'Data/SoundFX/Global/Skidding.wav'
Loaded Data File 'Data/SoundFX/Global/LoseRings.wav'
Loaded Data File 'Data/SoundFX/Global/Hurt.wav'
Loaded Data File 'Data/SoundFX/Global/Charge.wav'
Loaded Data File 'Data/SoundFX/Global/Release.wav'
Loaded Data File 'Data/SoundFX/Global/Destroy.wav'
Loaded Data File 'Data/SoundFX/Global/LampPost.wav'
Loaded Data File 'Data/SoundFX/Global/BlueShield.wav'
Loaded Data File 'Data/SoundFX/Global/Spring.wav'
Loaded Data File 'Data/SoundFX/Global/SignPost.wav'
Loaded Data File 'Data/SoundFX/Global/ScoreAdd.wav'
Loaded Data File 'Data/SoundFX/Global/ScoreTotal.wav'
Loaded Data File 'Data/SoundFX/Global/SpecialRing.wav'
Loaded Data File 'Data/SoundFX/Global/SpecialWarp.wav'
Loaded Data File 'Data/SoundFX/Global/Explosion.wav'
Loaded Data File 'Data/SoundFX/Global/Rolling.wav'
Loaded Data File 'Data/SoundFX/Global/Flying.wav'
Loaded Data File 'Data/SoundFX/Global/Tired.wav'
Loaded Data File 'Data/SoundFX/Global/MenuButton.wav'
Loaded Data File 'Data/SoundFX/Global/Select.wav'
Loaded Data File 'Data/SoundFX/Global/BackButton.wav'
Loaded Data File 'Data/SoundFX/Global/1Up.wav'
Loaded Data File 'Data/SoundFX/Global/Landing.wav'
Loaded Data File 'Data/SoundFX/Global/Sliding.wav'
Loaded Data File 'Data/SoundFX/Global/Catch.wav'
Loaded Data File 'Data/SoundFX/Global/BonusPoints.wav'
Loaded Data File 'Data/SoundFX/Global/SpikesMove.wav'
Loaded Data File 'Data/SoundFX/Global/BubbleShield.wav'
Loaded Data File 'Data/SoundFX/Global/BubbleBounce.wav'
Loaded Data File 'Data/SoundFX/Global/FireShield.wav'
Loaded Data File 'Data/SoundFX/Global/FireDash.wav'
Loaded Data File 'Data/SoundFX/Global/LightningShield.wav'
Loaded Data File 'Data/SoundFX/Global/LightningJump.wav'
Loaded Data File 'Data/SoundFX/Global/InstaShield.wav'
Loaded Data File 'Data/SoundFX/Global/Transform.wav'
Loaded Data File 'Data/SoundFX/Global/Spike.wav'
Loaded Data File 'Data/SoundFX/Global/Event.wav'
Loaded Data File 'Data/SoundFX/Global/Resume.wav'
Loaded Data File 'Data/Game/SystemText.gif'
Loaded Data File 'Data/Game/SystemText.gif'
Set Object (0) name to: Blank Object
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, TwoPlayerVS)
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName9)
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName10)
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName11)
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName12)
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName13)
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName14)
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName15)
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName16)
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Failed to load string... (en, SaveStageName27)
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/StringList.txt'
Loaded Data File 'Data/Game/CreditsMobile.txt'
Loaded Data File 'Data/Game/Menu/CWLogo.png'
Loaded Data File 'Data/Game/Menu/Sega.png'
Loaded Data File 'Data/Game/Menu/Heading_EN@1x.png'
Loaded Data File 'Data/Game/Menu/Heading_EN.fnt'
Loaded Data File 'Data/Game/Menu/Label_EN@1x.png'
Loaded Data File 'Data/Game/Menu/Label_EN.fnt'
Loaded Data File 'Data/Game/Menu/Text_EN.png'
Loaded Data File 'Data/Game/Menu/Text_EN.fnt'
Loaded Data File 'Data/Game/GameConfig.bin'
Loaded Data File 'Data/Game/SystemText.gif'
Loaded Data File 'Data/Game/SystemText.gif'
Loaded File 'Data/Game/GameConfig.bin'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Loaded File 'Data/Game/GameConfig.bin'
Set SFX (0) name to: Jump
Set SFX (1) name to: Ring L
Set SFX (2) name to: Ring R
Set SFX (3) name to: Skidding
Set SFX (4) name to: Lose Rings
Set SFX (5) name to: Hurt
Set SFX (6) name to: Charge
Set SFX (7) name to: Release
Set SFX (8) name to: Destroy
Set SFX (9) name to: Star Post
Set SFX (10) name to: Blue Shield
Set SFX (11) name to: Spring
Set SFX (12) name to: Sign Post
Set SFX (13) name to: Score Add
Set SFX (14) name to: Score Total
Set SFX (15) name to: Special Ring
Set SFX (16) name to: Warp
Set SFX (17) name to: Explosion
Set SFX (18) name to: Rolling
Set SFX (19) name to: Flying
Set SFX (20) name to: Tired
Set SFX (21) name to: Menu Move
Set SFX (22) name to: Menu Select
Set SFX (23) name to: Menu Back
Set SFX (24) name to: Life
Set SFX (25) name to: Landing
Set SFX (26) name to: Sliding
Set SFX (27) name to: Catch
Set SFX (28) name to: Bonus Points
Set SFX (29) name to: Spikes Move
Set SFX (30) name to: Bubble Shield
Set SFX (31) name to: Bubble Bounce
Set SFX (32) name to: Fire Shield
Set SFX (33) name to: Fire Dash
Set SFX (34) name to: Lightning Shield
Set SFX (35) name to: Lightning Jump
Set SFX (36) name to: Insta Shield
Set SFX (37) name to: Transform
Set SFX (38) name to: Spike
Set SFX (39) name to: Event
Set SFX (40) name to: Resume
Loaded File 'Data/SoundFX/Global/Jump.wav'
Loaded File 'Data/SoundFX/Global/Ring.wav'
Loaded File 'Data/SoundFX/Global/Ring.wav'
Loaded Data File 'Data/SoundFX/Global/Skidding.wav'
Loaded Data File 'Data/SoundFX/Global/LoseRings.wav'
Loaded Data File 'Data/SoundFX/Global/Hurt.wav'
Loaded File 'Data/SoundFX/Global/Charge.wav'
Loaded File 'Data/SoundFX/Global/Release.wav'
Loaded Data File 'Data/SoundFX/Global/Destroy.wav'
Loaded File 'Data/SoundFX/Global/LampPost.wav'
Loaded Data File 'Data/SoundFX/Global/BlueShield.wav'
Loaded File 'Data/SoundFX/Global/Spring.wav'
Loaded Data File 'Data/SoundFX/Global/SignPost.wav'
Loaded Data File 'Data/SoundFX/Global/ScoreAdd.wav'
Loaded Data File 'Data/SoundFX/Global/ScoreTotal.wav'
Loaded File 'Data/SoundFX/Global/SpecialRing.wav'
Loaded File 'Data/SoundFX/Global/SpecialWarp.wav'
Loaded Data File 'Data/SoundFX/Global/Explosion.wav'
Loaded Data File 'Data/SoundFX/Global/Rolling.wav'
Loaded Data File 'Data/SoundFX/Global/Flying.wav'
Loaded File 'Data/SoundFX/Global/Tired.wav'
Loaded File 'Data/SoundFX/Global/MenuButton.wav'
Loaded File 'Data/SoundFX/Global/Select.wav'
Loaded File 'Data/SoundFX/Global/BackButton.wav'
Loaded File 'Data/SoundFX/Global/1Up.wav'
Loaded Data File 'Data/SoundFX/Global/Landing.wav'
Loaded Data File 'Data/SoundFX/Global/Sliding.wav'
Loaded Data File 'Data/SoundFX/Global/Catch.wav'
Loaded Data File 'Data/SoundFX/Global/BonusPoints.wav'
Loaded File 'Data/SoundFX/Global/SpikesMove.wav'
Loaded File 'Data/SoundFX/Global/BubbleShield.wav'
Loaded File 'Data/SoundFX/Global/BubbleBounce.wav'
Loaded Data File 'Data/SoundFX/Global/FireShield.wav'
Loaded Data File 'Data/SoundFX/Global/FireDash.wav'
Loaded Data File 'Data/SoundFX/Global/LightningShield.wav'
Loaded Data File 'Data/SoundFX/Global/LightningJump.wav'
Loaded Data File 'Data/SoundFX/Global/InstaShield.wav'
Loaded File 'Data/SoundFX/Global/Transform.wav'
Loaded Data File 'Data/SoundFX/Global/Spike.wav'
Loaded Data File 'Data/SoundFX/Global/Event.wav'
Loaded Data File 'Data/SoundFX/Global/Resume.wav'
Couldn't load file 'Data/Game/Game.xml'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, TwoPlayerVS)
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName8)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName9)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName10)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName11)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName12)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName13)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName14)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName15)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName16)
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, SaveStageName14)
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/CreditsMobile.txt'

**Comment by MarioMastr** [comment]
here's the log when i try to enable the mod by forcing it in the modconfig.ini

Loaded Data File 'Bytecode/GlobalCode.bin'
loaded datapack '/Users/ashrafmohamed/Downloads/Sonic 3 v4/Data.rsdk'
Loaded File 'Data/Game/GameConfig.bin'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Initializing gamepads...
Found 0 gamepads!
Loaded File 'Data/Game/GameConfig.bin'
Set SFX (0) name to: Jump
Set SFX (1) name to: Ring L
Set SFX (2) name to: Ring R
Set SFX (3) name to: Skidding
Set SFX (4) name to: Lose Rings
Set SFX (5) name to: Hurt
Set SFX (6) name to: Charge
Set SFX (7) name to: Release
Set SFX (8) name to: Destroy
Set SFX (9) name to: Star Post
Set SFX (10) name to: Blue Shield
Set SFX (11) name to: Spring
Set SFX (12) name to: Sign Post
Set SFX (13) name to: Score Add
Set SFX (14) name to: Score Total
Set SFX (15) name to: Special Ring
Set SFX (16) name to: Warp
Set SFX (17) name to: Explosion
Set SFX (18) name to: Rolling
Set SFX (19) name to: Flying
Set SFX (20) name to: Tired
Set SFX (21) name to: Menu Move
Set SFX (22) name to: Menu Select
Set SFX (23) name to: Menu Back
Set SFX (24) name to: Life
Set SFX (25) name to: Landing
Set SFX (26) name to: Sliding
Set SFX (27) name to: Catch
Set SFX (28) name to: Bonus Points
Set SFX (29) name to: Spikes Move
Set SFX (30) name to: Bubble Shield
Set SFX (31) name to: Bubble Bounce
Set SFX (32) name to: Fire Shield
Set SFX (33) name to: Fire Dash
Set SFX (34) name to: Lightning Shield
Set SFX (35) name to: Lightning Jump
Set SFX (36) name to: Insta Shield
Set SFX (37) name to: Transform
Set SFX (38) name to: Spike
Set SFX (39) name to: Event
Set SFX (40) name to: Resume
Loaded File 'Data/SoundFX/Global/Jump.wav'
Loaded File 'Data/SoundFX/Global/Ring.wav'
Loaded File 'Data/SoundFX/Global/Ring.wav'
Loaded Data File 'Data/SoundFX/Global/Skidding.wav'
Loaded Data File 'Data/SoundFX/Global/LoseRings.wav'
Loaded Data File 'Data/SoundFX/Global/Hurt.wav'
Loaded File 'Data/SoundFX/Global/Charge.wav'
Loaded File 'Data/SoundFX/Global/Release.wav'
Loaded Data File 'Data/SoundFX/Global/Destroy.wav'
Loaded File 'Data/SoundFX/Global/LampPost.wav'
Loaded Data File 'Data/SoundFX/Global/BlueShield.wav'
Loaded File 'Data/SoundFX/Global/Spring.wav'
Loaded Data File 'Data/SoundFX/Global/SignPost.wav'
Loaded Data File 'Data/SoundFX/Global/ScoreAdd.wav'
Loaded Data File 'Data/SoundFX/Global/ScoreTotal.wav'
Loaded File 'Data/SoundFX/Global/SpecialRing.wav'
Loaded File 'Data/SoundFX/Global/SpecialWarp.wav'
Loaded Data File 'Data/SoundFX/Global/Explosion.wav'
Loaded Data File 'Data/SoundFX/Global/Rolling.wav'
Loaded Data File 'Data/SoundFX/Global/Flying.wav'
Loaded File 'Data/SoundFX/Global/Tired.wav'
Loaded File 'Data/SoundFX/Global/MenuButton.wav'
Loaded File 'Data/SoundFX/Global/Select.wav'
Loaded File 'Data/SoundFX/Global/BackButton.wav'
Loaded File 'Data/SoundFX/Global/1Up.wav'
Loaded Data File 'Data/SoundFX/Global/Landing.wav'
Loaded Data File 'Data/SoundFX/Global/Sliding.wav'
Loaded Data File 'Data/SoundFX/Global/Catch.wav'
Loaded Data File 'Data/SoundFX/Global/BonusPoints.wav'
Loaded File 'Data/SoundFX/Global/SpikesMove.wav'
Loaded File 'Data/SoundFX/Global/BubbleShield.wav'
Loaded File 'Data/SoundFX/Global/BubbleBounce.wav'
Loaded Data File 'Data/SoundFX/Global/FireShield.wav'
Loaded Data File 'Data/SoundFX/Global/FireDash.wav'
Loaded Data File 'Data/SoundFX/Global/LightningShield.wav'
Loaded Data File 'Data/SoundFX/Global/LightningJump.wav'
Loaded Data File 'Data/SoundFX/Global/InstaShield.wav'
Loaded File 'Data/SoundFX/Global/Transform.wav'
Loaded Data File 'Data/SoundFX/Global/Spike.wav'
Loaded Data File 'Data/SoundFX/Global/Event.wav'
Loaded Data File 'Data/SoundFX/Global/Resume.wav'
Couldn't load file 'Data/Game/Game.xml'
Loaded Data File 'Data/Game/SystemText.gif'
Loaded Data File 'Data/Game/SystemText.gif'
Set Object (0) name to: Blank Object
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, TwoPlayerVS)
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName8)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName9)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName10)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName11)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName12)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName13)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName14)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName15)
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, StageName16)
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Failed to load string... (en, SaveStageName14)
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/StringList.txt'
Loaded File 'Data/Game/CreditsMobile.txt'

**Comment by BigNate60** [comment]
Okay so it seems like there's supposed to be a Game.xml file in Data/Game, but it's not there. Same thing's happening to me so it's not isolated
