### ISSUE TITLE
act finish with signpost/capsule glitch

### ISSUE THREAD

**Issue by CarlGamerPro** [CalcuIator/v4-S3#4]
theres a glitch when sonic goes off screen, the game freezes, however the result music still works (and the ding sound goes by very fast)
The RSDKv4 version im using is the one in this build. I'm using the scripts from: https://github.com/Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation
Video:

https://user-images.githubusercontent.com/121400525/218329081-d33e9fab-30cb-4661-98fc-8ceb807f8206.mp4
This is probably happening because of the Act Finish object/script.

**Comment by CalcuIator** [comment]
Not entirely sure why this would happen, seems to be fine for me

Can you try using these scripts? 
[Scripts.zip](https://github.com/CalcuIator/v4-S3/files/10716894/Scripts.zip)

**Comment by CarlGamerPro** [comment]
It works now, thanks!
