### ISSUE TITLE
Can someone fix this?

### ISSUE THREAD

**Issue by CyanAngryBird** [CalcuIator/v4-S3#5]
Hello, i tried playing v4-S3, but it shows an error, I'm not using PC, I'm using the mobile, Can someone fix this issue?
![Screenshot_20230215-183721_RSDKv4](https://user-images.githubusercontent.com/97601268/219361414-324ddac7-2870-4cf5-80a8-12ff4022e7ed.png)
![Screenshot_20230215-183732_RSDKv4](https://user-images.githubusercontent.com/97601268/219361449-dfb9357e-1be5-47a6-9ca7-c97b6af41a4c.png)

**Comment by CarlGamerPro** [comment]
It looks like your using Sonic 2 with the mod, V4-S3 isn't compatible with sonic 2. Only Sonic 1.
